apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    openshift.io/cluster-monitoring: "true"
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    operator: volume-expander-operator
spec:
  selector:
    matchLabels:
      operator: volume-expander-operator
  replicas: 1
  template:
    metadata:
      labels:
        operator: volume-expander-operator
    spec:
      serviceAccountName: controller-manager
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: controller:latest
        name: manager
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      terminationGracePeriodSeconds: 10
